spring:
  application:
    name: da-assignment
  datasource:
    url: jdbc:h2:file:~/spring-boot-h2-db;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=false
    driverClassName: org.h2.Driver
    username: sa
    password: password
  jpa:
    hibernate:
      dialect: org.hibernate.dialect.H2Dialect
      ddl-auto: update
  h2:
    console:
      enabled: true
      path: /h2